{% set name = "diffpy.cmi" %}
{% set version = "3.1.1" %}
{% set python_min = "3.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/d/diffpy_cmi/diffpy_cmi-3.1.1.tar.gz
  sha256: ab4e902414b94a34c3442882448caff575043f3fab8b81e4a572c6ca4a6e67cd

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install --no-deps --ignore-installed .
  entry_points:
    - diffpy.cmi = diffpy.cmi.cli:main
    - cmi = diffpy.cmi.cli:main

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - setuptools-git-versioning >=2.0
    - pip

  run:
    - python >={{ python_min }}
    - numpy
    - scipy
    - packaging
    - pyyaml
    - requests # remove when print info test is fixed
    - matplotlib-base
    - diffpy.structure
    - diffpy.utils
    - diffpy.srfit
    - libobjcryst 2024.2.1
    - pyobjcryst
    - periodictable
    - libdiffpy
    - diffpy.srreal
test:
  requires:
    - python {{ python_min }}
    - pip
    - pytest

  source_files:
    - tests

  commands:
    - pip check
    - pytest

about:
  home: https://github.com/diffpy.cmi/diffpy.cmi/
  summary: "Complex modeling infrastructure: a modular framework for multi-modal modeling of scientific data."
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.rst
  description: |
    Welcome to diffpy.cmi, a complex modeling infrastructure for multi-modal analysis of scientific data. Diffpy.cmi is designed as an extensible complex modeling infrastructure. Users and developers can readily integrate novel data types and constraints into custom workflows. While widely used for advanced analysis of structural data, the framework is general and can be applied to any problem where model parameters are refined to fit calculated quantities to data. Diffpy.cmi is comprised of modular units called 'packs' and 'profiles' that facilitate tailored installations for specific scientific applications.
  doc_url: http://diffpy.cmi.github.io/diffpy.cmi/
  dev_url: https://github.com/diffpy.cmi/diffpy.cmi/

extra:
  recipe-maintainers:
    - sbillinge
    - cadenmyers13
    - Tieqiong
